### ISSUE TITLE
local server iffttt auth

### ISSUE THREAD

**Issue by yonubear** [OmerTu/GoogleHomeKodi#108]
where do we get the iffttt auth token from?

**Comment by keydon** [comment]
you are supposed to make one up yourself.
then you configure that in your settings of the node app and include the same token in the json body or your applet.

**Comment by yonubear** [comment]
ok then so it is just a password wasn't sure if it came from iffttt or what

Thanks,
Yonu

**Comment by yonubear** [comment]
sorry to be a pain but what does this error mean?

module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/reg/Desktop/kodi home/server.js:6:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by keydon** [comment]
it seems your local node installation does not have all required dependencies. did you execute the following command in your project root directory?
`npm install`

**Comment by yonubear** [comment]
ok i did npm install and now i get this

/home/reg/Desktop/kodi home/helpers.js:426
    let executions = [...Array(times)].map(() => action());
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/reg/Desktop/kodi home/server.js:9:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by p0psicles** [comment]
What is your node version? Run node --version

**Comment by yonubear** [comment]
v4.2.6

**Comment by p0psicles** [comment]
You need at least version 6. 8 recommended

**Comment by keydon** [comment]
@p0psicles we should add that info to the README section B.2
i will classify this as a bug to remind us about that.

**Comment by p0psicles** [comment]
Yes your right

**Comment by yonubear** [comment]
ok question how to i goto 6 or above the newest release i have available is what i inetalled

**Comment by p0psicles** [comment]
Use Google for installing on your OS.

**Comment by keydon** [comment]
Or you can try out running the app neatly contained in a docker container ready to work out of the box.
It is functional, but the documentation is not completed yet. but should be enough to get you up and running.
https://github.com/keydon/GoogleHomeKodi/tree/develop#b3-run-it-with-docker

**Comment by keydon** [comment]
docs improved in develop branch
