### ISSUE TITLE
Syntax error- Glitch

### ISSUE THREAD

**Issue by dvuder** [OmerTu/GoogleHomeKodi#114]
Hello all, 
I spent a long time trying to set up a local node but kept getting the same syntax error. Thought I was doing something wrong so I tried on Glitch and got the same. 

I set up a node on Glitch, Koditestconnection succeeds just fine on live test on Glitch

On IFTTT webhooks: 

URL: https://xxx/playmovie?q= TextField    (the ingredient)
Method: POST
Content Type: Application/json
Body: {"token":"xxx"}

Please help. Thanks
Collin

```
request failed
route:  
query:  { q: ' Matrix' }
error:  { SyntaxError: Unexpected token “ in JSON at position 1
    at Object.parse (native)
    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
    at /app/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
    at done (/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
  expose: true,
  statusCode: 400,
  status: 400,
  body: '{“token”:”connectplus”}',
  type: 'entity.parse.failed' }
body:  {}
```

**Comment by keydon** [comment]
your json body uses the wrong quotes.
maybe retype them manually if you copy & pasted them.

Bad:
```
{“token”:”connectplus”}
```

Good:
```
{"token":"connectplus"}
```

**Comment by dvuder** [comment]
Holy cow!
I was using IFTTT app on the iphone which does not seem to have the ability to use these quotes but when I used the desktop app it worked. 

I'll be honest I had no idea there were different types of quotes.

**Comment by keydon** [comment]
yeah i had to learn that the hard way too :)
