### ISSUE TITLE
won't start  syntax error on spread operator in line 428 of helpers.js???

### ISSUE THREAD

**Issue by den-dog** [OmerTu/GoogleHomeKodi#137]
Hi,

was installing the node to test it out, planning to use dweet.io as intermediate instead of opening up my router...

but didn't get there, make install all worked on 2 NPM warnings, but got stuck in launching the node server.js:
node server.js
/home/pi/GoogleHomeKodi/helpers.js:428
    let executions = [...Array(times)].map(() => action());
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/GoogleHomeKodi/server.js:9:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

code looks ok... wondering where to look to resolve this now...

hmm drop it, resolved the warning:
npm WARN engine dotenv@4.0.0: wanted: {"node":">=4.6.0"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.1","npm":"2.14.7"})

by forcing an nodejs update outside aptitude: raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh to get latest from source

**Comment by keydon** [comment]
yes, your node version was too old. at least v6 is required.
