### ISSUE TITLE
Doesn't work for me, fetchError ?

### ISSUE THREAD

**Issue by dedeludo** [OmerTu/GoogleHomeKodi#148]
Hi, thanks for your great work, i have a problem, can you help me please?

Request movie Babel on IFTT

Here the log of glitch:

Authentication succeeded
Movie request received to play "Babel"
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
request failed
route:  /playmovie
query:  { q: 'Babel' }
error:  { FetchError: request to http://????????.ddns.net:8090/jsonrpc failed, reason: connect ECONNREFUSED "IP EXT":8090
at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at Socket.socketErrorListener (_http_client.js:309:9)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at emitErrorNT (net.js:1277:8)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
name: 'FetchError',
message: 'request to http://?????????????.ddns.net:8090/jsonrpc failed, reason: connect ECONNREFUSED IP EXT:8090',
type: 'system',
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED' }
body:  { token: 'coco' }

Test troubleshooting:

http://YOUR_INTERNAL_KODI_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

--> WORKS FINE

http://??????????????.ddns.net:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

--> WORKS FINE

Edit: i have the same error (fetcherror) if i shutdown my NAS and if NAS/KODI switch on, do i have to install a software in KODI?

THANK YOU FOR YOUR HELP

**Comment by dedeludo** [comment]
ok i solved the problem, it was the Kodi port (8090 for me), it block in box, i changed 8080 and it works!!!!
