### ISSUE TITLE
error when playing specific episode

### ISSUE THREAD

**Issue by freeagent1384** [OmerTu/GoogleHomeKodi#150]
First off, great work man. Really love this. Thus far only seeing one issue when trying to play an episode using Kodi play $ episode # I get the error below:

```
Authentication succeeded
request failed
route:  /playepisode
query:  { q: 'It \' s Always Sunny in Philadelphia Season 1', e: '1' }
error:  TypeError: Cannot read property 'trim' of undefined
    at exports.kodiPlayEpisodeHandler (/home/node/app/helpers.js:847:38)
    at /home/node/app/server.js:36:9
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
    at next (/home/node/app/node_modules/express/lib/router/route.js:131:14)
body:  { token: 'XXXXXXXXXXX' }
```
This only happens thus far with It's Always Sunny... and I'm sure is related the the comma in It's.  Small thing to complain about but thought it worth mentioning.  Keep up the great work.

**Comment by keydon** [comment]
its actualy the upper-case "S" in "Season" that causes the error. fixed.
