### ISSUE TITLE
Unescaped characters

### ISSUE THREAD

**Issue by adridb** [OmerTu/GoogleHomeKodi#187]
Hello, I have node.js working but when I access to the port and try to make some request (/testconnection or /mute) it says allways:

Authentication succeeded
mute/unmute request received
Command sent = {"jsonrpc":"2.0","id":1,"method":"Application.SetMute","params":{"mute":"toggle"}}
request failed
route:  /mute
query:  {}
error:  TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:105:13)
    at request (http.js:41:10)
    at /home/node/app/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/home/node/app/node_modules/node-fetch/index.js:49:9)
    at Fetch (/home/node/app/node_modules/node-fetch/index.js:37:10)
    at Kodi.sendHTTP (/home/node/app/kodi-connection/api.js:31:16)
    at Kodi.send (/home/node/app/kodi-connection/api.js:65:21)
    at Object.result.(anonymous function) [as SetMute] (/home/node/app/kodi-connection/api.js:10:32)
    at exports.kodiMuteToggle (/home/node/app/helpers.js:804:29) 

Do anyone knoes what is happening? Thank you.

**Comment by keydon** [comment]
would you mind sharing your solution/cause with the group (if you were able to fix it at least)
