### ISSUE TITLE
Commit 8ca9c1a in server.js syntax error

### ISSUE THREAD

**Issue by jaaxx** [OmerTu/GoogleHomeKodi#219]
Removing that commit from server.js allows it to run.

**Comment by keydon** [comment]
please elaborate on that, what is the error message, what node version are you using?

**Comment by keydon** [comment]
ah nevermind, i can reproduce on glitch
```
} catch {

            ^


SyntaxError: Unexpected token {

    at createScript (vm.js:56:10)

    at Object.runInThisContext (vm.js:97:10)

    at Module._compile (module.js:549:28)

    at Object.Module._extensions..js (module.js:586:10)

    at Module.load (module.js:494:32)

    at tryModuleLoad (module.js:453:12)

    at Function.Module._load (module.js:445:3)

    at Module.runMain (module.js:611:10)

    at run (bootstrap_node.js:394:7)
```
