### ISSUE TITLE
Building fails (2-6-2019)

### ISSUE THREAD

**Issue by Tuumke** [OmerTu/GoogleHomeKodi#225]
```
root@dockers:/opt/docker# docker build --tag omertu/googlehomekodi https://github.com/OmerTu/GoogleHomeKodi.git
Sending build context to Docker daemon    574kB
Step 1/17 : FROM node:alpine as builder
alpine: Pulling from library/node
e7c96db7181b: Pull complete
41d5942c4680: Pull complete
48a61374e04d: Pull complete
Digest: sha256:67ca3b1ba6a0d8c52030d0e5d775ace600197371c56becf7e6e9ff8191850f58
Status: Downloaded newer image for node:alpine
 ---> 91acf04599c4
Step 2/17 : RUN apk add --no-cache python make g++
 ---> Running in 1716ceac77b2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/22) Installing binutils (2.31.1-r2)
(2/22) Installing gmp (6.1.2-r1)
(3/22) Installing isl (0.18-r0)
(4/22) Installing libgomp (8.3.0-r0)
(5/22) Installing libatomic (8.3.0-r0)
(6/22) Installing mpfr3 (3.1.5-r1)
(7/22) Installing mpc1 (1.0.3-r1)
(8/22) Installing gcc (8.3.0-r0)
(9/22) Installing musl-dev (1.1.20-r4)
(10/22) Installing libc-dev (0.7.1-r0)
(11/22) Installing g++ (8.3.0-r0)
(12/22) Installing make (4.2.1-r2)
(13/22) Installing libbz2 (1.0.6-r6)
(14/22) Installing expat (2.2.6-r0)
(15/22) Installing libffi (3.2.1-r6)
(16/22) Installing gdbm (1.13-r1)
(17/22) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(18/22) Installing ncurses-terminfo (6.1_p20190105-r0)
(19/22) Installing ncurses-libs (6.1_p20190105-r0)
(20/22) Installing readline (7.0.003-r1)
(21/22) Installing sqlite-libs (3.26.0-r3)
(22/22) Installing python2 (2.7.16-r1)
Executing busybox-1.29.3-r10.trigger
OK: 205 MiB in 38 packages
Removing intermediate container 1716ceac77b2
 ---> 0b2834b0e935
Step 3/17 : COPY package*.json ./
 ---> aa08a9c1a061
Step 4/17 : RUN npm install --production
 ---> Running in c59ce01631a6

> deasync@0.1.13 install /node_modules/deasync
> node ./build.js

make: Entering directory '/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:221,
                 from ../src/deasync.cc:3:
../../nan/nan_converters_43_inl.h: In static member function 'static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)':
../../nan/nan_converters_43_inl.h:18:51: warning: 'v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
       val->To ## TYPE(isolate->GetCurrentContext())                            \
                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro 'X'
 X(Boolean)
 ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:2524:63: note: declared here
                     V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
                                                               ^~~~~~~~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:221,
                 from ../src/deasync.cc:3:
../../nan/nan_converters_43_inl.h: In static member function 'static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)':
../../nan/nan_converters_43_inl.h:37:57: warning: 'v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro 'X'
 X(bool, Boolean)
 ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:2562:51: note: declared here
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^~~~~~~~~~~~
/root/.node-gyp/12.3.1/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:222,
                 from ../src/deasync.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)':
../../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to 'v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)'
                           , obj));
                                ^
In file included from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:4125:31: note: candidate: 'static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)'
   static MaybeLocal<Function> New(
                               ^~~
/root/.node-gyp/12.3.1/include/node/v8.h:4125:31: note:   no known conversion for argument 1 from 'v8::Isolate*' to 'v8::Local<v8::Context>'
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1064:78: warning: 'v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:2544:35: note: declared here
                     Local<String> ToString(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In member function 'void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)':
../../nan/nan.h:1855:64: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                                                                ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In member function 'void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)':
../../nan/nan.h:1861:42: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(key, value);
                                          ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In member function 'void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)':
../../nan/nan.h:1867:44: warning: 'bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(index, value);
                                            ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:3368:26: note: declared here
                     bool Set(uint32_t index, Local<Value> value));
                          ^~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const':
../../nan/nan.h:1873:61: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
         New(persistentHandle)->Get(New(key).ToLocalChecked()));
                                                             ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:3412:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                       ^~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const':
../../nan/nan.h:1879:55: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)->Get(key));
                                                       ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:3412:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                       ^~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const':
../../nan/nan.h:1884:57: warning: 'v8::Local<v8::Value> v8::Object::Get(uint32_t)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)->Get(index));
                                                         ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:3416:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
                                                       ^~~
/root/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/deasync.cc:3:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2208:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from /usr/include/c++/8.3.0/cassert:44,
                 from /root/.node-gyp/12.3.1/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:54,
                 from ../src/deasync.cc:3:
../../nan/nan_object_wrap.h: In destructor 'virtual Nan::ObjectWrap::~ObjectWrap()':
../../nan/nan_object_wrap.h:24:25: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(persistent().IsNearDeath());
                         ^~~~~~~~~~~
In file included from ../../nan/nan.h:2698,
                 from ../src/deasync.cc:3:
../../nan/nan_object_wrap.h: In member function 'void Nan::ObjectWrap::MakeWeak()':
../../nan/nan_object_wrap.h:67:34: warning: 'void v8::PersistentBase<T>::MarkIndependent() [with T = v8::Object]' is deprecated: Weak objects are always considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
     persistent().MarkIndependent();
                                  ^
In file included from /root/.node-gyp/12.3.1/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.3.1/include/node/v8.h:25,
                 from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h:567:22: note: declared here
       V8_INLINE void MarkIndependent());
                      ^~~~~~~~~~~~~~~
/root/.node-gyp/12.3.1/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from /usr/include/c++/8.3.0/cassert:44,
                 from /root/.node-gyp/12.3.1/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:54,
                 from ../src/deasync.cc:3:
../../nan/nan_object_wrap.h: In static member function 'static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)':
../../nan/nan_object_wrap.h:124:26: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(wrap->handle_.IsNearDeath());
                          ^~~~~~~~~~~
In file included from ../../nan/nan.h:52,
                 from ../src/deasync.cc:3:
../src/deasync.cc: At global scope:
/root/.node-gyp/12.3.1/include/node/node.h:556:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.node-gyp/12.3.1/include/node/node.h:590:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/deasync.cc:17:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(deasync, init)
 ^~~~~~~~~~~
In file included from ../src/deasync.cc:2:
/root/.node-gyp/12.3.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.node-gyp/12.3.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.node-gyp/12.3.1/include/node/v8.h:9817:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.node-gyp/12.3.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.node-gyp/12.3.1/include/node/v8.h:9817:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
make: *** [deasync.target.mk:107: Release/obj.target/deasync/src/deasync.o] Error 1
make: Leaving directory '/node_modules/deasync/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.18.0-20-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/deasync
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T18_27_11_600Z-debug.log
The command '/bin/sh -c npm install --production' returned a non-zero code: 1
```

**Comment by Tuumke** [comment]
Same when running:

```
curl -L -O https://github.com/OmerTu/GoogleHomeKodi/archive/master.tar.gz
tar xzf master.tar.gz
cd GoogleHomeKodi-master
docker build --tag omertu/googlehomekodi .
```
When running docker from: sinedied/googlehomekodi
it works. But i don't know if that is the same?!

**Comment by kotarokun** [comment]
same here…..

**Comment by serbanmarti** [comment]
For some reasons the package deasync@0.1.13 has issues.

A workaround would be getting the code locally, and then running the following commands:
- `npm install deasync@0.1.15`
- `npm audit fix`

After that I managed to build successfully.
