### ISSUE TITLE
Regular expression error when using brooker

### ISSUE THREAD

**Issue by Mr-Groch** [OmerTu/GoogleHomeKodi#253]
When I try to use broker, all requests ends with regular expression error:

```
Authentication succeeded
Broker processing phrase: 'switch to the polsat channel' (en)
request failed
route:  /broker
query:  { phrase: 'switch to the polsat channel' }
error:  SyntaxError: Invalid regular expression: /^play a random (?<genre>.+ )?movie( of year (?<year>\d+))?/: Invalid group
    at String.match (native)
    at exports.processRequest (/volume1/homes/groch/GoogleHomeKodi/broker.js:23:28)
    at /volume1/homes/groch/GoogleHomeKodi/server.js:45:9
    at Layer.handle [as handle_request] (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/layer.js:95:5)
    at next (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/route.js:137:13)
    at next (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/route.js:131:14)
    at next (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/route.js:131:14)
    at next (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/route.js:131:14)
    at next (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/route.js:131:14)
    at next (/volume1/homes/groch/GoogleHomeKodi/node_modules/express/lib/router/route.js:131:14)
body:  { token: '***' }
Sending command to kodi http://***.lan:8008/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "GUI.ShowNotification",
  "params": {
    "title": "GoogleHomeKodi",
    "message": "undefined: Invalid regular expression: /^play a random (?<genre>.+ )?movie( of year (?<year>\\d+))?/: Invalid group",
    "image": "error"
  }
}
```

When I deleted first item from en.json then error occurs on next... and so on...

**Comment by keydon** [comment]
You seem to use an pretty old nodejs version (9 or older), but you need 10 or higher for the broker to work.

**Comment by Mr-Groch** [comment]
OK, thanks, yous should update readme, in B.2, there is:

B.2 Set up local webserver (Click to expand instructions)
Install the Node.js application server on your target computer
Note: Required Version is 6.10 or above (8 preferred)

Unfortunately on Synology node v8 is the latest available...

**Comment by keydon** [comment]
yeah good point, I will update the readme.

And as I gather from #255 you can code. So the problem with node v8 is the regex feature of named groups. You could rewrite the `en.json` to use anonymous groups and adjust the code thats reading the match. At least the commands which only use the `q` parameter would then work.

**Comment by keydon** [comment]
Readme updated.
Ah and if you have a x86 synology model you might wanna try the docker hosting solution.
