### ISSUE TITLE
request failed: TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Kravatak76** [OmerTu/GoogleHomeKodi#256]
Hello, I set up my project in glitch according to procedure B1, and then created an applet in IFTTT to use the broker phrase. Unfortunately, I still receive the same error on all requests and I have not found a solution anywhere. Thank you for the advice.

Authentication succeeded
request failed
route:  /broker
query:  { Phrase: 'play an episode of black lightning' }
error:  TypeError: Cannot read property 'toLowerCase' of undefined
at exports.processRequest (/app/broker.js:29:39)
at /app/server.js:46:9
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:131:14)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:131:14)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:131:14)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:131:14)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:131:14)
    at next (/rbd/pnpm-volume/5a529713-c262-48d7-9d86-023c790e2be1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:131:14)
body:  { token: 'XXXXXXXXX' }
versions:  { http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
Sending command to kodi http://XXXXXXXXX:8080/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "GUI.ShowNotification",
  "params": {
    "title": "GoogleHomeKodi",
  
![ifttt_applet1](https://user-images.githubusercontent.com/15181800/69497810-597cc100-0ee1-11ea-9c38-57e7747ccf8e.JPG)
![ifttt_applet2](https://user-images.githubusercontent.com/15181800/69497811-597cc100-0ee1-11ea-9702-c87a25672ab7.JPG)

  "message": "undefined: Cannot read property 'toLowerCase' of undefined",
    "image": "error"
  }
}

**Comment by keydon** [comment]
the URL Field in the IFTTT-Applet is case-sensitive.
Meaning you need to write _*p*hrase_ will a lowercase _P_.

**Comment by Kravatak76** [comment]
omg, I copied it from the instructions, so I do not know how I got there such a stupid error. Thank you. it works now :)
