### ISSUE TITLE
broker error message ECONNRESET

### ISSUE THREAD

**Issue by mwink4689** [OmerTu/GoogleHomeKodi#279]
I am a real neophyte, but I finally got the broker app working. It plays movies that I request, etc. But I now get an error message and Kodi crashes immediately when I give the command "Kodi seek forward 20 minutes." Below is the output of the console. Can someone (in a simple explanation) help me solve this problem? Much appreciated.

Authentication succeeded
Broker processing phrase: 'seek forward 20 minutes' (en)
redirecting request to: 'kodiSeekForwardMinutes
Seek x minutes forwards request received
trying to parse:  20
parsed valid plain number: 20
Sending command to kodi http://192.168.10.84:9090/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "Player.Seek",
  "params": {
    "playerid": 0,
    "value": {
      "seconds": 1200
    }
  }
}
Sending command to kodi http://192.168.10.84:9090/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "Player.Seek",
  "params": {
    "playerid": 1,
    "value": {
      "seconds": 1200
    }
  }
}
request failed
route:  /broker
query:  { phrase: ' seek forward 20 minutes', q: '20' }
error:  FetchError: request to http://192.168.10.84:9090/jsonrpc failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (c:\node\GoogleHomeKodi\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to http://192.168.10.84:9090/jsonrpc failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
body:  { token: 'XXXXXX' }
versions:  {
  node: '12.16.1',
  v8: '7.8.279.23-node.31',
  uv: '1.34.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}

**Comment by keydon** [comment]
the crash itself seems to be a bug in kodi. But I can only reproduce that error, when no media is playing, so we could check for that beforehand.
Are you trying to seek forward, while nothing is playing?

**Comment by mwink4689** [comment]
no, the movie is already playing. After I give the command to seek forward, Kodi crashes.
